services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    ports:
      - "8083:8080"
    environment:
      DB_SERVER: mysql
      DB_PORT: 3306
      DB_NAME: project
      DB_USER: cee
      DB_PWD: cee
    depends_on:
      - mysql:
          condition: service_healthy
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project
      MYSQL_USER: cee
      MYSQL_PASSWORD: cee
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: cee
      PMA_PASSWORD: cee
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
